# Generated by Django 4.0.7 on 2023-04-30 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Name must be greater than 1 character')])),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('key', models.CharField(max_length=3)),
                ('loudness', models.FloatField()),
                ('mode', models.IntegerField()),
                ('speechiness', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
                ('spotify_id', models.CharField(max_length=25)),
                ('uri', models.CharField(max_length=45)),
                ('track_href', models.URLField()),
                ('analysis_url', models.URLField()),
                ('duration_in_ms', models.PositiveIntegerField()),
                ('time_signature', models.PositiveIntegerField()),
            ],
        ),
    ]
